### ISSUE TITLE
Ref of CBinding generated type

### ISSUE THREAD

**Issue by hros** [analytech-solutions/CBinding.jl#115]
I am seeing different results when creating a variable as `Ref(cbinding_data_type())` vs `x=cbinding_data_type(); Ref(x)`
Specifically, note the package `XXhash` (see [issue 114](https://github.com/analytech-solutions/CBinding.jl/issues/114)):
```julia
cr = Ref(libxxhash.XXH32_canonical_t())
libxxhash.XXH32_canonicalFromHash(cr, UInt32(555))
cr[].digest # = [0x00, 0x00, 0x02, 0x2b]
```
vs
```julia
c = libxxhash.XXH32_canonical_t()
libxxhash.XXH32_canonicalFromHash(Ref(c), UInt32(555))
c.digest # = [0x00, 0x00, 0x00, 0x00]
```

can you please explain the different behavior?

**Comment by krrutkow** [comment]
I'm guessing the first is the correct behavior?  Since in the second, creating a `Ref` is actually creating a copy of `c`, so passing `Ref(c)` to the function is actually passing a copy of `c` to the function and modifying that copy which is then discarded and the unmodified `c` is used.

**Comment by hros** [comment]
Thanks
Indeed, the first case is the correct/exprcted behavior.
If `Ref(x)` returns the address of a copy of `x`, how do you take the address of an existing variable?

BTW, the `C` type of the given example is a struct containing  an array of 4 bytes named `digest`. The array is shown to be of type `Carray{UInt8,  4,  4}`. How can I assign a Julia array of 4 bytes to that variable?

**Comment by krrutkow** [comment]
> how do you take the address of an existing variable?

You cannot get an address of a Julia struct, it must be a `Ref{cbinding_type}` or an instance allocated with `Libc.malloc` (gives you a `Ptr{cbinding_type}`) if you need to work with a memory address.  The biggest difference encountered is if you need to modify individual fields, then I would recommend using `Libc.malloc` since `Ref` is more all-or-nothing for making changes to the instance.

> How can I assign a Julia array of 4 bytes to that variable?

Using a pointer (allocated by `Libc.malloc` or if the C library returns a pointer to an object), then you can do the following to assign any length-of-4 iterable to it:
```julia
julia> using CBinding
       c``
       c"""
       struct S {
         char data[4];
       };
       """j
var"c\"struct S\""

julia> x = Libc.malloc(S)
Cptr{var"c\"struct S\""}(0x0000000002008250)

julia> x.data[] = "asdf"
"asdf"

julia> x[]
var"(c\"struct S\")" (4-byte struct)
  data = "asdf"

julia> x.data[] = ('1', '2', '3', '4')
('1', '2', '3', '4')

julia> x[]
var"(c\"struct S\")" (4-byte struct)
  data = "1234"

julia> x.data[] = ['A', 'B', 'C', 'D']
4-element Vector{Char}:
 'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)
 'B': ASCII/Unicode U+0042 (category Lu: Letter, uppercase)
 'C': ASCII/Unicode U+0043 (category Lu: Letter, uppercase)
 'D': ASCII/Unicode U+0044 (category Lu: Letter, uppercase)

julia> x[]
var"(c\"struct S\")" (4-byte struct)
  data = "ABCD"

julia> Libc.free(x)
```

**Comment by hros** [comment]
thanks!!!

I would appreciate your help on two other related question
1. When sending the address of arrays to the hash function I am getting an unwanted dependence on the specific Julia object rather the data,  please see [description on discourse](https://discourse.julialang.org/t/address-of-object/89695)
2. I would like to dispatch on the size of a vector:
```Julia
@inline function xxhash_fromcanonical(v::NTuple{4,UInt8}) 
    c = Libc.malloc(libxxhash.XXH32_canonical_t)
    c.digest = v
    h = libxxhash.XXH32_hashFromCanonical(c)
    Libc.free(c)
    return h
end

@inline function xxhash_fromcanonical(v::NTuple{8,UInt8})
    c = Libc.malloc(libxxhash.XXH64_canonical_t)
    c.digest = v
    h = libxxhash.XXH64_hashFromCanonical(c)
    Libc.free(c)
    return h
end
```
This only works If I pass a `Tuple`:
```Julia
@inline function xxhash_tocanonical(h::UInt64) 
    c = Libc.malloc(libxxhash.XXH64_canonical_t)
    libxxhash.XXH64_canonicalFromHash(c, h)
    res = Tuple(c.digest[])
    Libc.free(c)
    return res
end
```
but I can't a `Vector{Uint8}`, either generated by the user, or returning a vector in the previous function:
```Julia
@inline function xxhash_tocanonical(h::UInt64) 
    c = Libc.malloc(libxxhash.XXH64_canonical_t)
    libxxhash.XXH64_canonicalFromHash(c, h)
    res = copy(c.digest[])
    Libc.free(c)
    return res
end
```

**Comment by krrutkow** [comment]
Perhaps your examples are more like MWEs, but if not you should implement them more like:
```julia
@inline function xxhash_fromcanonical(v::NTuple{4,UInt8}) 
    c = Ref(libxxhash.XXH32_canonical_t(digest = v))
    h = libxxhash.XXH32_hashFromCanonical(c)
    return h
end
```
or
```julia
@inline function xxhash_fromcanonical(v::NTuple{4,UInt8}) 
    c = C_NULL
    try
        c = Libc.malloc(libxxhash.XXH32_canonical_t)
        c.digest = v
        h = libxxhash.XXH32_hashFromCanonical(c)
        return h
    finally
        c == C_NULL || Libc.free(c)
    end
end
```

1. Too pseudo-code-ish to assess a reason...  As Sukera said "A minimal working example showing your code would be helpful for diagnosing what’s going wrong." 
2. You cannot dispatch on the size of a `Vector` since it is not part of the type, but you can dispatch on `Vector{UInt8}` and convert to the appropriate `NTuple` though:

```julia
@inline xxhash_fromcanonical(v::Vector{UInt8}) = length(v) in (4, 8) ? xxhash_fromcanonical(Tuple(v)) : error("bad arg")
```

**Comment by krrutkow** [comment]
> dispatches to the appropriate implementation if the vector's length is 4 or 8.

It seems there is a misunderstanding of Julia's _type_ dispatch, the _type_ must have the size encoded in it in order to dispatch on size, which is why `NTuple` is able to be dispatched on.  With a `Vector`, the only option is a runtime branch to call the appropriate function (which will likely end up with multiple possible return types and further inefficiencies cascading from there).

> which I modified to accommodate the size of arrays and structs

The use of `Base.summarysize` is definitely incorrect, which is probably causing a bunch of "random" data being read from memory, hence the difference.  It depends on how you intend to use the hash function, but this works for the `a` and `b` arrays you defined:
```julia
@inline xxh32(data::Array, seed::Union{Int32,UInt32}=UInt32(0))::UInt32 = libxxhash.XXH32(data, sizeof(data), seed % UInt32)
```
You may need to have different code for when `data` is not a bits type (see `isbitstype`) or bits type array, since those types contain references to other objects (and hashing an object reference would probably not be the same every time).
