### ISSUE TITLE
@cextern turns global variable into function

### ISSUE THREAD

**Issue by sloede** [analytech-solutions/CBinding.jl#56]
I am trying to use the KROME chemistry package from within Julia. For a C header file with
```c
extern const int krome_nmols;
```

I created
```julia
using CBinding

@cbindings "/home/mschlott/gdrive/work/code/hackathon/KROME.jl/deps/krome/build/libkrome.so" begin
  @cextern krome_nmols::Cint
end
```

I expected was `krome_nmols` to be of type `Cglobal`, but instead it is a function that *returns* the `Cglobal`:
```julia
julia> typeof(krome_nmols)
typeof(krome_nmols)

julia> typeof(krome_nmols())
CBinding.Cglobal{Int32}
```
When using the more appropriate `Cconst(Cint)` instead of just `Cint`, the picture is the same. My question thus is: Am I using `CBinding` wrong? Or is the library header wrong? Or am I missing something in the `CBinding` docs?

**Comment by krrutkow** [comment]
Your usage is correct, you just discovered my scheme to rid the world of C global variables. :rofl: 

Actually, this is a good discussion topic...  Globals are the most awkward part of binding with C, and I am looking for ideas on how to make it more elegant.  It is not (yet) possible to bind the global in C to an actual global in Julia, because the value would be fetched from C when the module is precompiled, not when it is actually loaded/used.  Therefore, sharing global state objects between C and Julia requires a dynamic fetching (why it is a function call rather than an object).

Originally CBinding was using the `__init__` function to bind the globals, but that approach caused a lot of overhead code generation.  The current, fairly ugly syntax for working with globals should produce just the load/store instructions with no excess code generation and seamlessly extend the `Caccessor` mechanism for non-aggregate variable types as well.  Making the global a function was also a workaround for type name collisions resulting from CBinding dropping the `struct`/`union`/`enum` annotations (`struct S` in C becomes `S` in Julia).  However, similar name collisions with enumeration values can still happen, so the best solution might be to create annotated type names in Julia (something like `var"struct S"`, but less obnoxious).

**Comment by sloede** [comment]
OK, I think I understand your point. I have to admit, though, I am really not knowledgeable enough about the finer details of C bindings in Julia. Thus, I don't think I can offer much input on the implementation details.

OTOH, from a user perspective it seems to be very verbose to both have to call a function and dereference its return value. Thus, I think it would be great if there were a way to go from
```julia
nmols = krome_nmols()[]
```
to
```julia
nmols = krome_nmols[]
```
or
```julia
nmols = krome_nmols()
```

I would very much prefer the first syntax, as it would naturally extend to array access and modifying values, e.g.,
```julia
krome_species_densities[idx] = vlaue
```
but I don't know if this in violation of the issues you mentioned above.

Anyhow, thanks for the fast reply, I know now what to do in my case. It might be helpful to others, though, to mention this behavior explicitly (or to link to your explanation above) in the README. Please let me know if there is anything else I can help with.

**Comment by bhalonen** [comment]
@sloede are you planning on publishing the wrapper? Sounds like an interesting software

**Comment by sloede** [comment]
Absolutely! It is in a private repo at the moment since nobody in our team has used it yet beyond some initial examples, and I didn't want to publish it in such an experimental and fragile state. To be precise, so far the only thing that has been tested is the "hello" test. However, if you have an application in mind and wouldn't mind playing being the ultimate alpha user, I can also give you access to it and/or make it public.

**Comment by krrutkow** [comment]
The v1.0 release now creates bindings for global variables as pointers which can be accessed and dereferenced the same way as any pointer.
```jl
structPtr.field[] = 123  # assign the field of a global structure `structPtr->field = 123;`
structPtr.field[]  # read the field `structPtr->field;`
arrayPtr[3][] = 456  # assign array element in a global array `(*arrayPtr)[2] = 456;`
ptr[] = 789  # assign global variable `(*ptr) = 789;`
```
